---
title: "Final Project"
author: "Junyuan Zhang"
date: "12/11/2021"
output: html_document
---



```{r}
library(tidyverse)
#read the file
bubble = read.csv("bubblewrap.csv", header = TRUE)


line_speed = bubble$line_speed
loading = bubble$loading

reformat_loading = as.factor(loading)
reformat_speed = as.factor(line_speed)
# reformat the loading and line_speed to characters so that can be used for 2 way anova
bubblewrap = bubble %>%
  mutate(loading_reform = reformat_loading) %>%
  mutate(speed_reform = reformat_speed)

#fit the full model with intersection
full = lm(rate ~ loading_reform*speed_reform ,data = bubblewrap)
anova(full)
# by anova table the intersection term is not significant
```
```{r}
# fit the additive model with loading and speed without intersection
add = lm(rate ~ loading_reform + speed_reform, data = bubblewrap)
summary(add)
# fit the reduced model that have only loading and line_speed each test for individual factor
reduce_load = lm(rate ~ loading_reform, data = bubblewrap)
reduce_speed = lm(rate ~ speed_reform, data = bubblewrap)

anova(reduce_load, add)
anova(reduce_speed, add)
# both significant

```

```{r}
TukeyHSD(aov(rate ~ loading_reform + speed_reform, data = bubblewrap))
#loading type 4 and line_speed 37 combine is best combination 
```

```{r}
library(lmtest)
# check for normality
plot(add,which = 2)
hist(add$residuals)
shapiro.test(add$residuals)
# reject the normality by shapiro test

bptest(add)
# constant variance assumption is good
```

```{r}
#transform the data to recover normality

bubblewrap$rate_cub = (bubblewrap$rate)^3
new = lm(rate_cub ~ loading_reform + speed_reform, data = bubblewrap)
shapiro.test(new$residuals)
# the transfortion solved the normality
hist(new$residuals)
plot(new, which = 2)
```
